task: inference
source: demo/images/inference/image.png
labels: demo/labels/coco_labels.txt
data:
  batch_size: 16
  shuffle: False
  pin_memory: True
  data_augment: {}
nms:
  min_confidence: 0.1
  min_iou: 0.5